# Spring properties
spring:
  profiles:
    active: h2
  application:
     name: jac
  freemarker:
    enabled: true
  thymeleaf:
    cache: false                     # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory
